version: 2
updates:
  - package-ecosystem: docker
    directory: "/cmd/uplink/Dockerfile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/cmd/satellite/Dockerfile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/web/satellite/Dockerfile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/cmd/storagenode/Dockerfile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/cmd/versioncontrol/Dockerfile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: "/."
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
