language: go
go: 1.12.1

go_import_path: "storj.io/storj"

git:
  depth: 1

cache:
  directories:
    - /home/travis/cache

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
      psql -c 'create database teststorj' -U postgres;
    fi;

before_install:
  - source scripts/setup-gopath.sh
matrix:
  include:
    ### windows tests ###
    - env: MODE=windows-tests
      os: windows
      services:
        - redis
      cache:
        directories:
          - "%HOME%/cache"
      before_install:
        - powershell -executionpolicy bypass -File scripts/setup-gopath.ps1
      install:
        - go install -race ./...
      script:
        - go test -count 3 ./storage/...
        - go test -count 3 ./storagenode/pieces
        - go test -count 3 ./storagenode/piecestore

  fast_finish: true

addons:
  postgresql: "9.5"
