language: go

go:
  - 1.11.x
env:
  - GO111MODULE=on

#cache:
#  directories:
#    # cache built tools
#    - "$GOPATH/bin"
#    # cache go modules
#    - "$GOPATH/pkg"
#    # cache pip
#    - "$HOME/.cache/pip"

services:
  - redis

before_install:
  # move things to the right location
  - source scripts/travis-deps.sh

install:
  # download all modules
  - go get .
  # build dependencies
  - go install -v ./...
  # move all dependencies to vendor directory
  - go mod vendor
  # flatten vendor to src
  - cp -r ./vendor/* $GOPATH/src/
  - rm -rf ./vendor
  # install linters
  - GO111MODULE=off make build-dev-deps
  
script:
  - GO111MODULE=off make lint
  - GO111MODULE=off make test
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  - make test-captplanet
