language: go
go: 1.12.2

go_import_path: "storj.io/storj"

git:
  depth: 1

cache:
  directories:
    - /home/travis/cache

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
      psql -c 'create database teststorj' -U postgres;
    fi;

matrix:
  allow_failures:
    - os: windows
  include:
      script:
        - go install ./cmd/statreceiver
  fast_finish: true
