language: go
go: 1.12.1

git:
  depth: 1

cache:
  directories:
    - /home/travis/cache

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
      psql -c 'create database teststorj' -U postgres;
    fi;

matrix:
  include:
    - env:
        - GO111MODULE=on
        - CI=travis
        - STORJ_POSTGRES_TEST=postgres://postgres@localhost/teststorj?sslmode=disable
      services:	
        - redis	
        - postgresql
      install:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b ${GOPATH}/bin v1.13
      script:
        - go run scripts/use-ports.go -from 1024 -to 10000 &
        - GOMOD=ci.mod go run ci.go

addons:
  postgresql: "9.5"