language: go

go: 1.11.x
go_import_path: "storj.io/storj"

git:
  depth: 1

cache:
  directories:
    - /home/travis/cache

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
      psql -c 'create database teststorj' -U postgres;
    fi;

before_install:
  - source scripts/setup-gopath.sh
matrix:
  allow_failures:
    - os: windows # allow failures on windows because it's slow
  include:
    ### tests ###
    - env:
        - MODE=tests
        - STORJ_POSTGRES_TEST=postgres://postgres@localhost/teststorj?sslmode=disable
      services:
        - redis
        - postgresql
      install:
        - pushd ~
        - GOBIN=${GOPATH}/bin GOPATH=~/gotools go get github.com/mfridman/tparse
        - popd
        - go install -race ./...
      script:
        - go test -parallel 64 -count 10 -run TestRetrieve -race -cover -coverprofile=.coverprofile -json -timeout 9m ./pkg/piecestore/psserver | tparse -all -top

  fast_finish: true

addons:
  postgresql: "9.5"
