language: go

go:
  - 1.10.x

before_install:
  - source scripts/travis-deps.sh

install:
  - make build-dev-deps

service:
  - redis-server

script:
  - make test
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
