language: go

go:
  - 1.11.x
env:
  - GO111MODULE=on

cache:
  directories:
    # cache built tools
    - "$GOPATH/bin"
    # cache go modules
    - "$GOPATH/pkg/mod"
    # cache tooling, to avoid redownloading
    # adding them separately to avoid conflicting with github.com/storj
    - "$GOPATH/src/github.com/golang/protobuf/protoc-gen-go"
    - "$GOPATH/src/github.com/mattn/goveralls"
    - "$GOPATH/src/golang.org/x/tools/cover"
    - "$GOPATH/src/github.com/modocache/gover"
    - "$GOPATH/src/github.com/alecthomas/gometalinter"
    - "$GOPATH/src/golang.org/x/"

services:
  - redis

before_install:
  - source scripts/travis-deps.sh

install:
  - GO111MODULE=off make build-dev-deps
  - go get .

script:
  - make test
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  - make test-captplanet
