version: "3"
services:
  storage-node:
    image: storjlabs/storage-node:${VERSION}
    environment:
    - SATELLITE_ADDR=satellite:7777
    links:
    - satellite
  satellite:
    image: storjlabs/satellite:${VERSION}
    command: --mock-overlay.nodes QM-62cCsr4KYBDTPgTAa_5Zm1DGImR39SJ_UKtRfAAA=:172.18.0.4:7777
    environment:
    - API_KEY=abc123
    - IDENTITY_ADDR=:7777
    - BOOTSTRAP_ADDR=localhost:8080
    links:
    - redis
    depends_on:
    - redis
  redis:
    image: redis
  uplink:
    image: storjlabs/uplink:${VERSION}
    command: --min-threshold 1 --max-threshold 1 --repair-threshold 1 --success-threshold 1
    environment:
    - SATELLITE_ADDR=satellite:7777
    - API_KEY=abc123
    ports:
    - 7777:7777
