apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.Name }}-config"
data:
  config.yaml: |-
    # path to static resources
    console.static-dir: "{{ .Values.static.console }}"
    # path to email templates source
    mail.template-path: "{{ .Values.static.mail }}"
    # path to static resources
    marketing.static-dir: "{{ .Values.static.marketing }}"

    # public address to listen on
    server.address: 0.0.0.0:7777

    # log all GRPC traffic to zap logger
    server.debug-log-traffic: false

    # private address to listen on
    server.private-address: 0.0.0.0:7778

    # path to the certificate chain for this identity
    identity.cert-path: /root/.local/share/storj/identity/satellite/identity.cert

    # path to the private key for this identity
    identity.key-path: /root/.local/share/storj/identity/satellite/identity.key

    # the minimum log level to log
    log.level: debug

    # can be stdout, stderr, or a filename
    log.output: stdout

    server.revocation-dburl: bolt:///app/revocations.db

    # the path for storage node db services to be created on
    kademlia.db-path: /app/kademlia

    # server address of the graphql api gateway and frontend app
    console.address: 0.0.0.0:10100

    # sender email address
    mail.from: Storj <jess-satellite-test@storj.io>

    # smtp server address
    mail.smtp-server-address: smtp.gmail.com:587
